require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/AndOr:
  EnforcedStyle: conditionals

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/RedundantSelf:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
